steps:
    - id: "Running docker compose"
      name: "gcr.io/$PROJECT_ID/docker-compose:1.24.0"
      args: ["-f", "docker-compose.cloudbuild.yml", "up", "-d"]

    - id: "Running docker ps"
      name: "gcr.io/$PROJECT_ID/docker"
      args: ["ps"]
