version: "3"

services:
    app:
        container_name: app
        build: .
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        container_name: nginx
        build: .docker/nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        container_name: db
        command: --innodb-use-native-aio=0
        image: mysql:5.7
        tty: true
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
